#!/usr/bin/env python
import sys
import subprocess
from threading import Thread


param=sys.argv

h5master=param[1]
imglist=param[2:]


print("Converting to JPG")

def convert(imgnb):
    name=h5master.split("_master")[0]

    converto2cbf="eiger2cbf "+h5master+" "+imgnb+" "+name+"_"+imgnb+".cbf"
    subprocess.call(converto2cbf, shell=True)



    convert2jpeg="diff2jpeg "+name+"_"+imgnb+".cbf"
    subprocess.call(convert2jpeg, shell=True)


    clean_up="rm "+name+"_"+imgnb+".cbf"
    subprocess.call(clean_up, shell=True)





for i in imglist:        
    t = Thread(target=convert, args=(i,))
    t.start()

